# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nlsNotAsfgjvNKuVG7l6L5uaYyHjbek8
"""

import numpy as np

def ch_ro(x, n, alpha, mu, *args):
    r = len(x)

    k_prime = len(list(filter(lambda f: f < x[0], x)))
    l_prime = len(list(filter(lambda f: f == x[0], x)))
    g_prime = k_prime + 0.5 * (l_prime + 1)

    one = ((n + alpha) / (r + alpha)) * g_prime
    two = 0.5 * ((n - r) / (r + alpha))
    three = (n - r) * (alpha * mu(x[0], *args)) / (r + alpha)

    g_hat = one - two + three
    return g_hat