# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nlsNotAsfgjvNKuVG7l6L5uaYyHjbek8
"""

from scipy.stats import norm
from scipy.integrate import quad
import numpy as np

def cMaxCorrNor(alpha, k, rho):
    def r(x, n):
        def inner_int(s):
            return norm.cdf((s * np.sqrt(rho) + x) / np.sqrt(1 - rho))**n * norm.pdf(s)
        result, _ = quad(inner_int, -np.inf, np.inf)
        return result

    pts = np.arange(3.5, 0, step=-0.01)
    for i in range(len(pts)):
        if r(pts[i], k) <= (1 - alpha):
            return pts[i]

    return None  # In case no value satisfies the condition