# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nlsNotAsfgjvNKuVG7l6L5uaYyHjbek8
"""

import numpy as np
from statsmodels.distributions.empirical_distribution import ECDF



def ferg_df(x, alpha, mu, n_points):
    x = np.sort(x)
    n = len(x)
    Fn = ECDF(x)

    temp_x = np.linspace(np.min(x), np.max(x), num=n_points)

    f_n = Fn(temp_x)
    f_0 = mu(temp_x)

    mu_n = (alpha / (alpha + n)) * f_0 + (n / (alpha + n)) * f_n
    return mu_n