# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nlsNotAsfgjvNKuVG7l6L5uaYyHjbek8
"""

import numpy as np
from scipy.stats import norm

def pHayStonLSA(h, k, delta=0.001):
    """
    Uses Hayter-Liu 1996 method.
    """
    our_grid = np.arange(-8, 8, delta)
    init_grid = norm.cdf(our_grid + h)

    if k > 2:
        for i in range(3, k + 1):
            new_grid = np.cumsum(init_grid * norm.pdf(our_grid) * delta) + \
                       init_grid * (norm.cdf(our_grid + h) - norm.cdf(our_grid))
            init_grid = new_grid

    return 1 - np.sum(norm.pdf(our_grid) * init_grid * delta)